name: Generate snake game

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *" # Changed cron syntax to run every 12 hours at 0 minutes past the hour
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository (updated to use Node.js 20 compatible version)
      - name: Checkout Repository
        uses: actions/checkout@v3 # Updated from v2 to v3 for Node.js 20 compatibility

      # Create dist directory if it doesn't exist
      - name: Create dist directory
        run: mkdir -p dist # Ensures the dist directory exists

      # Generate Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: rifqee23
          svg_out_path: dist/github-contribution-grid-snake2.svg
          snake_color: 'blue'

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
