name: Generate snake game

on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *" # Run every 12 hours at the 0th minute
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3 # Updated to Node.js 20 compatible version

      # Create dist directory if it doesn't exist
      - name: Create dist directory
        run: mkdir -p dist # Ensures the dist directory exists

      # Generate Snake Animation
      - name: Generate Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: rifqee23
          svg_out_path: dist/github-contribution-grid-snake2.svg

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3 # Updated to Node.js 20 compatible version
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
